# Generated by Django 5.0.4 on 2024-05-14 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersRating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achivment_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Achivment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('achivments_category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachersRating.achivment_category')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Achivment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Achivment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachersRating.achivment')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachersRating.teacher')),
            ],
        ),
    ]
