# Generated by Django 5.1.5 on 2025-05-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersRating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_achievment_file',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee_achievment_publication',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
