# Generated by Django 5.1.5 on 2025-02-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersRating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_achievment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
