# Generated by Django 5.1.5 on 2025-03-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersRating', '0002_alter_employee_achievment_conference_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_achievment',
            name='publication_data',
            field=models.DateField(null=True),
        ),
    ]
