# Generated by Django 5.1.5 on 2025-02-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersRating', '0002_employee_achievment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_achievment',
            name='verif_doc',
            field=models.FileField(blank=True, null=True, upload_to='verification_documents/'),
        ),
    ]
