# Generated by Django 5.0.4 on 2024-05-14 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersRating', '0002_achivment_category_achivment_teacher_achivment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_achivment',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Score_Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('Achivment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachersRating.achivment')),
            ],
        ),
    ]
