# Generated by Django 5.1.5 on 2025-03-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersRating', '0003_alter_employee_achievment_verif_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
