# Generated by Django 5.1.4 on 2024-12-22 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersRating', '0003_teacher_achivment_score_score_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teachersRating.teacher'),
        ),
    ]
