# Generated by Django 5.1.5 on 2025-03-02 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersRating', '0004_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievment_groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='achievment',
            name='parent_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='achievment',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teachersRating.achievment_groups'),
        ),
    ]
