# Generated by Django 5.1.5 on 2025-03-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersRating', '0005_achievment_groups_achievment_parent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
